### ISSUE TITLE
Internal Server Error with Keycloak Webapp

### ISSUE THREAD

**Issue by zepouet** [thomasdarimont/vertx-playground#3]
Hello,

Sorry but no way to run your project with Keycloack with different JVM release
I add this code to display the StackTrace. Thanks @tsegismont

```
        Router router = Router.router(vertx);

        router.errorHandler(500, rc -> {
            System.err.println("Handling failure");
            Throwable failure = rc.failure();
            if (failure != null) {
                failure.printStackTrace();
            }
        });
```

```
[INFO] Handling failure
[INFO] java.lang.IllegalStateException: Request must have a content-type header to decode a multipart request
[INFO] 	at io.vertx.core.http.impl.HttpServerRequestImpl.setExpectMultipart(HttpServerRequestImpl.java:436)
[INFO] 	at io.vertx.ext.web.impl.HttpServerRequestWrapper.setExpectMultipart(HttpServerRequestWrapper.java:286)
[INFO] 	at demo.MainVerticle.lambda$start$2(MainVerticle.java:52)
[INFO] 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
[INFO] 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
[INFO] 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$6(SessionHandlerImpl.java:276)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$8(SessionHandlerImpl.java:306)
[INFO] 	at io.vertx.ext.web.sstore.impl.LocalSessionStoreImpl.get(LocalSessionStoreImpl.java:88)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.doGetSession(SessionHandlerImpl.java:291)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.getSession(SessionHandlerImpl.java:287)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:248)
[INFO] 	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:36)
[INFO] 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
[INFO] 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
[INFO] 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
[INFO] 	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
[INFO] 	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
[INFO] 	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
[INFO] 	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
[INFO] 	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
[INFO] 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
[INFO] 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
[INFO] 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
[INFO] 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:163)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[INFO] 	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[INFO] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[INFO] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[INFO] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[INFO] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[INFO] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[INFO] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[INFO] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] 	at java.base/java.lang.Thread.run(Thread.java:830)
```

If I remove all the code relative between lines from 41 to 95 in your code, the verticle answers correctly but without the nice feature :)

Maybe a regression elsewhere or the problem is me... Very great articles. It is a pleasure to read them !

Thanks. 
Nicolas.

**Comment by zepouet** [comment]
The behaviour between Vert.x release 3.8.5 and 3.9.3 seems different. Thanks

**Comment by tsegismont** [comment]
@zepouet did you mean @thomasdarimont ?

**Comment by thomasdarimont** [comment]
@zepouet this is fixed with https://github.com/thomasdarimont/vertx-playground/commit/153d861217b8d103b9fbd9858b016fbbc4a8516b
